"""
Autogenerated ledger builder for Hegemon.
Derived from docs/LEDGER_GOVERNANCE.md (and docs/LEDGER.md where present).
"""
import sqlite3
import pathlib
import hashlib
import datetime

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DB_PATH = REPO_ROOT / "data" / "HEGEMON-AUDIT-LEDGER.sqlite"

SCHEMA = """
CREATE TABLE IF NOT EXISTS audit_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TEXT,
  actor TEXT,
  action TEXT,
  details TEXT,
  hash TEXT
);
CREATE TABLE IF NOT EXISTS economic_metrics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  metric_key TEXT,
  metric_value REAL,
  period TEXT
);
CREATE TABLE IF NOT EXISTS decision_trails (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  council_vote TEXT,
  proposal TEXT,
  outcome TEXT,
  ledger_ref TEXT
);
"""


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        h.update(f.read())
    return h.hexdigest()


def init_db():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.executescript(SCHEMA)
    conn.commit()
    conn.close()


if __name__ == "__main__":
    init_db()
    print("Ledger created ->", DB_PATH)
    for doc in ["ARCHITECTURE.md", "LEDGER_GOVERNANCE.md", "VISUAL_IDENTITY.md"]:
        p = REPO_ROOT / "docs" / doc
        if p.exists():
            print(f"{p.name}: SHA256 {sha256_file(p)} @ {datetime.datetime.utcnow().isoformat()} UTC")
